services:
  # 1. Main Node.js Backend
  - type: web
    name: smart-agri-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ML_SERVICE_URL
        fromService:
          type: web
          name: smart-agri-ml
          property: hostport
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: smart-agri-frontend
          property: url
          
  # 2. Machine Learning Sidecar Service
  - type: web
    name: smart-agri-ml
    env: python
    buildCommand: pip install -r ml-model/requirements.txt && pip install gunicorn && python ml-model/crop_recommendation/train_crop_model.py
    startCommand: env ML_PORT=$PORT gunicorn --bind 0.0.0.0:$PORT backend.app:app

  # 3. React Frontend
  - type: web
    name: smart-agri-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE_URL
        fromService:
          type: web
          name: smart-agri-backend
          property: url
